theme = "docuapi"
languageCode = "en-us"
baseurl = "https://docuapi.netlify.com/"
title = "Nash Link API Documentation"

disableKinds = ["taxonomyTerm"]

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = false

defaultContentLanguage = "en"

canonifyurls = "true"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = "github-ascii"
    [markup.goldmark.renderer]
        unsafe = true

[module]
[module.hugoVersion]
[[module.imports]]
# We include the theme by "../.." above, but we need one module import for Hugo to detect us as a Hugo Module.
path="github.com/bep/empty-hugo-module"

[params]
search = true

# Configure the language example tabs.
# [[params.language_tabs]]
# key = "shell"
# name = "Shell"
[[params.language_tabs]]
key = "javascript"
name = "JavaScript"
[[params.language_tabs]]
key = "php"
name = "PHP"
# [[params.language_tabs]]
# key = "python"
# name = "Python"

#Languages
[languages]

[languages.en]
languageName = "English"
weight = 1
title = "Nash Link API Documentation"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true
